# data storage
## global map for relative pose estimation using lidar frontend
map_path: /home/kevin/Documents/multisensor_fusion_for_mapping_and_localization/src/multisensor_localization/slam_data/map/filtered_map.pcd
## scan context index for map matching
scan_context_path: /home/kevin/Documents/multisensor_fusion_for_mapping_and_localization/src/multisensor_localization/slam_data/scan_context   

# point cloud map & measurement processors 
## global map filter
global_map_filter: voxel_filter                                 # options：voxel_filter, no_filter

## local map segmenter 
box_filter_size: [-150.0, 150.0, -150.0, 150.0, -150.0, 150.0]  # min_x, max_x, min_y, max_y, min_z, max_z
## local map filtering
local_map_filter: voxel_filter                                  # options: voxel_filter, no_filter

## current frame filter
frame_filter: voxel_filter                                      # options: voxel_filter, no_filter

## relative pose estimation using lidar frontend
registration_method: NDT_CPU                                    # options: NDT, NDT_CPU 

## map matching using scan context
map_matching_method: scan_context                               # options: scan_context


# configuration parameters
## filter parameters
voxel_filter:
    global_map:
        leaf_size: [0.9, 0.9, 0.9]
    local_map:
        leaf_size: [0.5, 0.5, 0.5]
    frame:
        leaf_size: [1.5, 1.5, 1.5]

## registration parameters
NDT:
    res : 1.0
    step_size : 0.1
    trans_eps : 0.01
    max_iter : 30
NDT_CPU:
    res : 1.0
    step_size : 0.1
    trans_eps : 0.01
    max_iter : 30
## ScanContext parameters
scan_context:
    # ROI definition
    max_radius: 80.0
    max_theta: 360.0
    # resolution
    num_rings: 20
    num_sectors: 60
    # ring key indexing interval
    indexing_interval: 1
    # min. key frame sequence distance
    min_key_frame_seq_distance: 100
    # num. of nearest-neighbor candidates to check
    num_candidates: 5
    # sector key fast alignment search ratio
    #   avoid brute-force match using sector key
    fast_alignment_search_ratio: 0.1
    # scan context distance threshold for proposal generation
    #   0.4-0.6 is good choice for using with robust kernel (e.g., Cauchy, DCS) + icp fitness threshold 
    #   if not, recommend 0.1-0.15
    scan_context_distance_thresh: 0.15